In [1]:
import pandas as pd
import numpy as np


In [2]:
record=pd.read_excel("car price p.xlsx")
record

car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std   
1         2          3       alfa-romero stelvio      gas        std   
2         3          1  alfa-romero Quadrifoglio      gas        std   
3         4          2               audi 100 ls      gas        std   
4         5          2                audi 100ls      gas        std   
..      ...        ...                       ...      ...        ...   
200     201         -1           volvo 145e (sw)      gas        std   
201     202         -1               volvo 144ea      gas      turbo   
202     203         -1               volvo 244dl      gas        std   
203     204         -1                 volvo 246   diesel      turbo   
204     205         -1               volvo 264gl      gas      turbo   

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
0          two  convertible        rwd          front       88.6  ...   
1          two  convertible        rwd          front       88.6  ...   
2          two    hatchback        rwd          front       94.5  ...   
3         four        sedan        fwd          front       99.8  ...   
4         four        sedan        4wd          front       99.4  ...   
..         ...          ...        ...            ...        ...  ...   
200       four        sedan        rwd          front      109.1  ...   
201       four        sedan        rwd          front      109.1  ...   
202       four        sedan        rwd          front      109.1  ...   
203       four        sedan        rwd          front      109.1  ...   
204       four        sedan        rwd          front      109.1  ...   

     enginesize  fuelsystem  boreratio  stroke compressionratio horsepower  \
0           130        mpfi       3.47    2.68              9.0        111   
1           130        mpfi       3.47    2.68              9.0        111   
2           152        mpfi       2.68    3.47              9.0        154   
3           109        mpfi       3.19    3.40             10.0        102   
4           136        mpfi       3.19    3.40              8.0        115   
..          ...         ...        ...     ...              ...        ...   
200         141        mpfi       3.78    3.15              9.5        114   
201         141        mpfi       3.78    3.15              8.7        160   
202         173        mpfi       3.58    2.87              8.8        134   
203         145         idi       3.01    3.40             23.0        106   
204         141        mpfi       3.78    3.15              9.5        114   

     peakrpm citympg  highwaympg    price  
0       5000      21          27  13495.0  
1       5000      21          27  16500.0  
2       5000      19          26  16500.0  
3       5500      24          30  13950.0  
4       5500      18          22  17450.0  
..       ...     ...         ...      ...  
200     5400      23          28  16845.0  
201     5300      19          25  19045.0  
202     5500      18          23  21485.0  
203     4800      26          27  22470.0  
204     5400      19          25  22625.0  

[205 rows x 26 columns]

In [13]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
record['fueltype']= le.fit_transform(record['fueltype'])
  
record['fueltype'].unique()

array([1, 0])

In [15]:
record['aspiration']= le.fit_transform(record['aspiration'])
  
record['aspiration'].unique()

array([0, 1])

In [16]:

record['doornumber']= le.fit_transform(record['doornumber'])
  
record['doornumber'].unique()

array([1, 0])

In [17]:

record['carbody']= le.fit_transform(record['carbody'])
  
record['carbody'].unique()

array([0, 2, 3, 4, 1])

In [18]:

record['enginelocation']= le.fit_transform(record['enginelocation'])
  
record['enginelocation'].unique()

array([0, 1])

In [19]:
record['drivewheel']= le.fit_transform(record['drivewheel'])
  
record['drivewheel'].unique()

array([2, 1, 0])

In [24]:
record['enginetype']= le.fit_transform(record['enginetype'])
  
record['enginetype'].unique()    

array([0, 5, 3, 2, 6, 4, 1])

In [25]:
record['cylindernumber']= le.fit_transform(record['cylindernumber'])
  
record['cylindernumber'].unique() 

array([2, 3, 1, 4, 5, 6, 0])

In [26]:
record['fuelsystem']= le.fit_transform(record['fuelsystem'])
record['fuelsystem'].unique() 

array([5, 1, 4, 0, 7, 2, 3, 6])

In [27]:
record.head()

symboling  fueltype  aspiration  doornumber  carbody  drivewheel  \
0          3         1           0           1        0           2   
1          3         1           0           1        0           2   
2          1         1           0           1        2           2   
3          2         1           0           0        3           1   
4          2         1           0           0        3           0   

   enginelocation  wheelbase  carlength  carwidth  ...  enginesize  \
0               0       88.6      168.8      64.1  ...         130   
1               0       88.6      168.8      64.1  ...         130   
2               0       94.5      171.2      65.5  ...         152   
3               0       99.8      176.6      66.2  ...         109   
4               0       99.4      176.6      66.4  ...         136   

   fuelsystem  boreratio  stroke  compressionratio  horsepower  peakrpm  \
0           5       3.47    2.68               9.0         111     5000   
1           5       3.47    2.68               9.0         111     5000   
2           5       2.68    3.47               9.0         154     5000   
3           5       3.19    3.40              10.0         102     5500   
4           5       3.19    3.40               8.0         115     5500   

   citympg  highwaympg    price  
0       21          27  13495.0  
1       21          27  16500.0  
2       19          26  16500.0  
3       24          30  13950.0  
4       18          22  17450.0  

[5 rows x 24 columns]

In [21]:
record.drop(['CarName','car_ID'],axis=1,inplace=True)

In [22]:
record.head()

symboling  fueltype  aspiration  doornumber  carbody  drivewheel  \
0          3         1           0           1        0           2   
1          3         1           0           1        0           2   
2          1         1           0           1        2           2   
3          2         1           0           0        3           1   
4          2         1           0           0        3           0   

   enginelocation  wheelbase  carlength  carwidth  ...  enginesize  \
0               0       88.6      168.8      64.1  ...         130   
1               0       88.6      168.8      64.1  ...         130   
2               0       94.5      171.2      65.5  ...         152   
3               0       99.8      176.6      66.2  ...         109   
4               0       99.4      176.6      66.4  ...         136   

   fuelsystem boreratio stroke  compressionratio horsepower  peakrpm  citympg  \
0        mpfi      3.47   2.68               9.0        111     5000       21   
1        mpfi      3.47   2.68               9.0        111     5000       21   
2        mpfi      2.68   3.47               9.0        154     5000       19   
3        mpfi      3.19   3.40              10.0        102     5500       24   
4        mpfi      3.19   3.40               8.0        115     5500       18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 24 columns]

In [3]:
record.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    object 
 3   fueltype          205 non-null    object 
 4   aspiration        205 non-null    object 
 5   doornumber        205 non-null    object 
 6   carbody           205 non-null    object 
 7   drivewheel        205 non-null    object 
 8   enginelocation    205 non-null    object 
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    object 
 15  cylindernumber    205 non-null    object 
 16  enginesize        205 non-null    int64  
 1

In [4]:
record.describe()

car_ID   symboling   wheelbase   carlength    carwidth   carheight  \
count  205.000000  205.000000  205.000000  205.000000  205.000000  205.000000   
mean   103.000000    0.834146   98.756585  174.049268   65.907805   53.724878   
std     59.322565    1.245307    6.021776   12.337289    2.145204    2.443522   
min      1.000000   -2.000000   86.600000  141.100000   60.300000   47.800000   
25%     52.000000    0.000000   94.500000  166.300000   64.100000   52.000000   
50%    103.000000    1.000000   97.000000  173.200000   65.500000   54.100000   
75%    154.000000    2.000000  102.400000  183.100000   66.900000   55.500000   
max    205.000000    3.000000  120.900000  208.100000   72.300000   59.800000   

        curbweight  enginesize   boreratio      stroke  compressionratio  \
count   205.000000  205.000000  205.000000  205.000000        205.000000   
mean   2555.565854  126.907317    3.329756    3.255415         10.142537   
std     520.680204   41.642693    0.270844    0.313597          3.972040   
min    1488.000000   61.000000    2.540000    2.070000          7.000000   
25%    2145.000000   97.000000    3.150000    3.110000          8.600000   
50%    2414.000000  120.000000    3.310000    3.290000          9.000000   
75%    2935.000000  141.000000    3.580000    3.410000          9.400000   
max    4066.000000  326.000000    3.940000    4.170000         23.000000   

       horsepower      peakrpm     citympg  highwaympg         price  
count  205.000000   205.000000  205.000000  205.000000    205.000000  
mean   104.117073  5125.121951   25.219512   30.751220  13276.710571  
std     39.544167   476.985643    6.542142    6.886443   7988.852332  
min     48.000000  4150.000000   13.000000   16.000000   5118.000000  
25%     70.000000  4800.000000   19.000000   25.000000   7788.000000  
50%     95.000000  5200.000000   24.000000   30.000000  10295.000000  
75%    116.000000  5500.000000   30.000000   34.000000  16503.000000  
max    288.000000  6600.000000   49.000000   54.000000  45400.000000


# EXPLORATORY DATA ANALYSIS

In [5]:
import dtale
import seaborn as sns


In [6]:
record=pd.read_excel("car price p.xlsx")
dtale.show(record, ignore_duplicate=True)

2021-08-11 22:26:22,190 - INFO     - NumExpr defaulting to 4 threads.


Exception on /dtale/charts/_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\hp\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\hp\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\hp\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\hp\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\hp\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\hp\anaconda3\lib\site-packages\dash\dash.py", line 1096, in dispatch
    response.set_data(func

2021-08-11 22:40:03,436 - ERROR    - Exception on /dtale/charts/_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\hp\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\hp\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\hp\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\hp\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\hp\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\hp\anaconda3\lib\site-packages\dash\dash.py", line 1096, i

Exception occurred while processing request: '<' not supported between instances of 'numpy.ndarray' and 'str'
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\lib\site-packages\dtale\views.py", line 101, in _handle_exceptions
    return func(*args, **kwargs)
  File "C:\Users\hp\anaconda3\lib\site-packages\dtale\views.py", line 3237, in network_data
    nodes = sorted(nodes)
TypeError: '<' not supported between instances of 'numpy.ndarray' and 'str'


2021-08-11 23:08:50,533 - ERROR    - Exception occurred while processing request: '<' not supported between instances of 'numpy.ndarray' and 'str'
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\lib\site-packages\dtale\views.py", line 101, in _handle_exceptions
    return func(*args, **kwargs)
  File "C:\Users\hp\anaconda3\lib\site-packages\dtale\views.py", line 3237, in network_data
    nodes = sorted(nodes)
TypeError: '<' not supported between instances of 'numpy.ndarray' and 'str'


In [28]:
# Model Building
from sklearn.model_selection import train_test_split
X = record.drop(columns='price')
y = record['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

# Creating Random Forest Model
from sklearn.ensemble import RandomForestRegressor
Regressor= RandomForestRegressor(n_estimators=20)
Regressor.fit(X_train, y_train)


RandomForestRegressor(n_estimators=20)

In [57]:
X.shape


(205, 23)

In [42]:
y.shape

(205,)

In [44]:
np.shape
np.reshape(-1,1)

array([-1])

In [45]:
y_pred=Regressor.predict(X_train)
y_pred

array([16698.30835   , 34363.4       , 14441.5       , 11287.35      ,
        7582.7       ,  7122.83666667, 14444.75      , 12969.83333333,
        8673.75      , 21912.95835   ,  7164.25      ,  7954.05      ,
        9698.65833333, 17088.7       , 18441.85      , 10515.86666667,
       17766.35      ,  9822.05      ,  6321.75333333,  6148.7       ,
       14749.5       ,  9972.9       ,  9228.54166667, 12260.        ,
       14234.        ,  8364.05      ,  6071.5       ,  9870.15      ,
        7785.5       ,  7154.85      ,  7989.8       ,  6011.55      ,
        7288.8       ,  7283.55      , 16597.5       ,  7469.        ,
       12894.95      ,  8214.2       , 15242.75      , 17309.5       ,
       20846.45      ,  8177.1       , 14933.75      ,  8383.6       ,
       33716.75      , 12742.95      , 13638.25      , 18939.4       ,
        8399.9       ,  9228.54166667, 16442.85      ,  9698.65833333,
        8984.8       , 13148.55      ,  6890.5       , 15452.35      ,
      

In [58]:
Regressor.score(X_test, y_test)

0.898451569176056